name: identity 
base: core22 
adopt-info: identity
grade: stable
confinement: strict
compression: lzo
license: GPL-3.0
source-code: https://gitlab.gnome.org/YaLTeR/identity
website: https://gitlab.gnome.org/YaLTeR/identity
issues: https://github.com/soumyaDghosh/identity-snap

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

parts:   
  rustup:
    plugin: rust
    source: .
    rust-channel: "1.76"
    override-build: ""
    override-prime: ""

  identity:
    after: [ rustup ]
    plugin: meson
    source: https://gitlab.gnome.org/YaLTeR/identity.git
    source-tag: 'v0.6.0'
    source-depth: 1
    parse-info: [usr/share/metainfo/org.gnome.gitlab.YaLTeR.Identity.metainfo.xml]
    meson-parameters:
      - --prefix=/snap/identity/current/usr
    build-snaps:
      - ffmpeg-2204-sdk
      - blueprint-compiler
    build-packages:
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
    stage-packages:
      - gstreamer1.0-plugins-bad
    build-environment:
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
      - PKG_CONFIG_PATH: /snap/ffmpeg-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig:$PKG_CONFIG_PATH
      - PATH: ${HOME}/.cargo/bin:/snap/ffmpeg-2204-sdk/current/usr/bin:$PATH
      - LD_LIBRARY_PATH: /snap/ffmpeg-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET:$LD_LIBRARY_PATH
      - GI_TYPELIB_PATH: /snap/gnome-42-2204-sdk/current/usr/lib/girepository-1.0:/snap/gnome-42-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0
    organize: 
      snap/identity/current: .

  cleanup:
    after:  # Make this part run last; list all your other parts here
      - identity
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core22
      - gnome-42-2204
    build-packages:
      - execstack
    override-prime: |
      set -eux
      for snap in "core22" "gnome-42-2204" "ffmpeg-2204"; do  # List all content-snaps and base snaps you're using here
          cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "$CRAFT_PRIME/{}" \;
      done
      cd
      
slots:
  identity:
    interface: dbus
    bus: session
    name: org.gnome.gitlab.YaLTeR.Identity

plugs:
  ffmpeg-2204:
    interface: content
    target: ffmpeg-platform
    default-provider: ffmpeg-2204

apps:
  identity:
    command: usr/bin/identity
    common-id: org.gnome.gitlab.YaLTeR.Identity
    extensions: [ gnome ]
    environment:
      GDK_DEBUG: portals
      PATH: $SNAP/ffmpeg-platform/usr/bin:$PATH
      LD_LIBRARY_PATH: $SNAP/ffmpeg-platform/usr/lib/$CRAFT_ARCH_TRIPLET:$LD_LIBRARY_PATH:$GI_TYPELIB_PATH:$GST_PLUGIN_PATH:$LIBGL_DRIVERS_PATH
    plugs:
      - home
      - removable-media
